name: odc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # Back-end services
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.4
  firebase_analytics: ^10.4.3
  firebase_crashlytics: ^3.3.3

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # UI
  flutter_animate: ^4.2.0
  responsive_builder: ^0.7.0
  lottie: ^2.4.0 
  loading_animation_widget: ^1.2.0+4
  sidebarx: ^0.16.0
  blur: ^3.1.0
  dotted_border: ^2.0.0+3
  date_time_picker: ^2.1.0
  infinite_carousel: ^1.0.3

  # Utils
  email_validator: ^2.1.17
  url_strategy: ^0.2.0
  flutter_dropzone: ^3.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  file_picker: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
    - assets/images/OpenSourceImages/
    - assets/images/text/
    - assets/images/formations/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Italic-VariableFont_wght.ttf
          style: italic
